(function(t){'use strict';if(typeof define==='function'&&define.amd){define(['jquery'],t)}
else if(typeof module!=='undefined'&&module.exports){module.exports=t(require('jquery'))}
else{t(jQuery)}})(function(t){var a=-1,r=-1,i=function(t){return parseFloat(t)||0},s=function(e){var o=1,a=t(e),n=null,r=[];a.each(function(){var e=t(this),a=e.offset().top-i(e.css('margin-top')),s=r.length>0?r[r.length-1]:null;if(s===null){r.push(e)}
else{if(Math.floor(Math.abs(n-a))<=o){r[r.length-1]=s.add(e)}
else{r.push(e)}};n=a});return r},n=function(e){var i={byRow:!0,property:'height',target:null,remove:!1};if(typeof e==='object'){return t.extend(i,e)};if(typeof e==='boolean'){i.byRow=e}
else if(e==='remove'){i.remove=!0};return i},e=t.fn.matchHeight=function(i){var r=n(i);if(r.remove){var o=this;this.css(r.property,'');t.each(e._groups,function(t,e){e.elements=e.elements.not(o)});return this};if(this.length<=1&&!r.target){return this};e._groups.push({elements:this,options:r});e._apply(this,r);return this};e.version='master';e._groups=[];e._throttle=80;e._maintainScroll=!1;e._beforeUpdate=null;e._afterUpdate=null;e._rows=s;e._parse=i;e._parseOptions=n;e._apply=function(r,l){var o=n(l),a=t(r),c=[a],f=t(window).scrollTop(),p=t('html').outerHeight(!0),h=a.parents().filter(':hidden');h.each(function(){var e=t(this);e.data('style-cache',e.attr('style'))});h.css('display','block');if(o.byRow&&!o.target){a.each(function(){var i=t(this),e=i.css('display');if(e!=='inline-block'&&e!=='flex'&&e!=='inline-flex'){e='block'};i.data('style-cache',i.attr('style'));i.css({'display':e,'padding-top':'0','padding-bottom':'0','margin-top':'0','margin-bottom':'0','border-top-width':'0','border-bottom-width':'0','height':'100px','overflow':'hidden'})});c=s(a);a.each(function(){var e=t(this);e.attr('style',e.data('style-cache')||'')})};t.each(c,function(e,r){var n=t(r),a=0;if(!o.target){if(o.byRow&&n.length<=1){n.css(o.property,'');return};n.each(function(){var e=t(this),n=e.attr('style'),i=e.css('display');if(i!=='inline-block'&&i!=='flex'&&i!=='inline-flex'){i='block'};var r={'display':i};r[o.property]='';e.css(r);if(e.outerHeight(!1)>a){a=e.outerHeight(!1)};if(n){e.attr('style',n)}
else{e.css('display','')}})}
else{a=o.target.outerHeight(!1)};n.each(function(){var e=t(this),r=0;if(o.target&&e.is(o.target)){return};if(e.css('box-sizing')!=='border-box'){r+=i(e.css('border-top-width'))+i(e.css('border-bottom-width'));r+=i(e.css('padding-top'))+i(e.css('padding-bottom'))};e.css(o.property,(a-r)+'px')})});h.each(function(){var e=t(this);e.attr('style',e.data('style-cache')||null)});if(e._maintainScroll){t(window).scrollTop((f/p)*t('html').outerHeight(!0))};return this};e._applyDataApi=function(){var e={};t('[data-match-height], [data-mh]').each(function(){var i=t(this),r=i.attr('data-mh')||i.attr('data-match-height');if(r in e){e[r]=e[r].add(i)}
else{e[r]=i}});t.each(e,function(){this.matchHeight(!0)})};var o=function(i){if(e._beforeUpdate){e._beforeUpdate(i,e._groups)};t.each(e._groups,function(){e._apply(this.elements,this.options)});if(e._afterUpdate){e._afterUpdate(i,e._groups)}};e._update=function(i,n){if(n&&n.type==='resize'){var s=t(window).width();if(s===a){return};a=s};if(!i){o(n)}
else if(r===-1){r=setTimeout(function(){o(n);r=-1},e._throttle)}};t(e._applyDataApi);t(window).bind('load',function(t){e._update(!1,t)});t(window).bind('resize orientationchange',function(t){e._update(!0,t)})});;Number.prototype.formatMoney=function(e,r,t){var o=this,e=isNaN(e=Math.abs(e))?2:e,r=r==undefined?'.':r,t=t==undefined?',':t,a=o<0?'-':'',n=String(parseInt(o=Math.abs(Number(o)||0).toFixed(e))),i=(i=n.length)>3?i%3:0;return a+(i?n.substr(0,i)+t:'')+n.substr(i).replace(/(\d{3})(?=\d)/g,'$1'+t)+(e?r+Math.abs(o-n).toFixed(e).slice(2):'')};(function(e){e(document).ready(function(){e('.view-product-hot .views-row').matchHeight({byRow:!0,property:'height',target:null,remove:!1});e('.view-product-list .views-row').matchHeight({byRow:!1,property:'height',target:null,remove:!1});e('.view-ho-so-nang-luc .views-row').matchHeight({byRow:!1,property:'height',target:null,remove:!1});e('.views-field-field-embed a').magnificPopup({disableOn:700,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:!1,fixedContentPos:!1});e('.view-partner .views-field-field-image img').each(function(){var t=e(this).width();e(this).css({'height':Math.round(t*9/16)+'px'})});e('.html').on('change','#webform-client-form-26 input,#webform-client-form-26 select',function(){var t=e('.html').find('#webform-client-form-26');if(t.find('#edit-submitted-layout-left-name').val()!=''&&t.find('#edit-submitted-layout-left-type').val()!=''&&t.find('#edit-submitted-layout-left-office').val()!=''&&t.find('#edit-submitted-layout-left-phone').val()!=''&&t.find('#edit-submitted-layout-right-number').val()!=''&&t.find('#edit-submitted-layout-right-so-lan-thue').val()!=''&&t.find('#edit-submitted-layout-right-email').val()!=''&&t.find('#edit-submitted-layout-right-lease-term').val()!=''){t.find('.webform-component--layout-right--price-1 .price-list .price').hide();t.find('.webform-component--layout-right--price-1').show();var i=0,r=t.find('#edit-submitted-layout-left-type').val();if(r=='Nhà nước'){t.find('.webform-component--layout-right--price-1 .price-list .price-1').show();i=parseInt(t.find('.webform-component--layout-right--price-1 .price-list .price-1').attr('data-price'))}
else if(r=='Công ty'){t.find('.webform-component--layout-right--price-1 .price-list .price-2').show();i=parseInt(t.find('.webform-component--layout-right--price-1 .price-list .price-2').attr('data-price'))}
else if(r=='Cá nhân'){t.find('.webform-component--layout-right--price-1 .price-list .price-3').show();i=parseInt(t.find('.webform-component--layout-right--price-1 .price-list .price-3').attr('data-price'))}
else{};var o=parseInt(t.find('#edit-submitted-layout-right-number').val()),n=parseInt(t.find('#edit-submitted-layout-right-lease-term').val()),a=o*n*i;t.find('.price-total').text(a.formatMoney(0,'.',',')+'đ')}
else{t.find('.webform-component--layout-right--price-1').hide()}})})})(jQuery);